### ISSUE TITLE
About the parallel bug in the code

### ISSUE THREAD

**Issue by hongbo-sun** [PRIS-CV/An-Erudite-FGVC-Model#1]
Thanks for your kindly sharing code. There is an issue, when running the code with two or more cards (using dataparallel),  the error happens as follows. Could you please share your solution? It would be very helpful. Single card is ok, but it is two slow for training.

Besides, could you please share your paper in a arxiv version? Then more details can be found and your excellent work can be spread more fluently. Thank you very much.

Traceback (most recent call last):
  File "main.py", line 440, in <module>
    train(epoch)
  File "main.py", line 341, in train
    task_model.adapt(adaptation_loss)  # computes gradient, update task_model in-place
  File "/home/sunhongbo/anaconda3/envs/u_modal/lib/python3.6/site-packages/learn2learn/algorithms/maml.py", line 169, in adapt
    self.module = maml_update(self.module, self.lr, gradients)
UnboundLocalError: local variable 'gradients' referenced before assignment

**Comment by tongyujun1999** [comment]
The paper link is now attached. So far, our code has been running on a single GPU. We will release a version that supports multi-GPU running in the future.
